### ISSUE TITLE
No stack traces for errors thrown by node_modules ?

### ISSUE THREAD

**Issue by p-j** [opbeat/opbeat-node#104]
Hi,

We've been using opbeat for a while and truly enjoying it, thank you for that :)

Recently we've split the business logic, helpers and other parts of our Express App into modules that we require. It allows us to share logic among projects and better isolate domain responsibility as well as write better tests.

The downside we've seen is that now we don't have stack traces anymore in opbeat when one of these module fails.

Here is an example (note: we use bunyan as logger, hence the formatting)

```
[2016-11-25T12:21:54.578Z] ERROR: screen-api/2589 on dev-vizeat: Places not found
    Error: Places not found
      at rp.then.then.ifttt (/path/to/expressApp/node_modules/vizeat-helpers/lib/geolocater.js:23:109)
      at /path/to/expressApp/node_modules/vizeat-helpers/lib/ifttt.js:25:40
      at tryCatcher (/path/to/expressApp/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/path/to/expressApp/node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (/path/to/expressApp/node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (/path/to/expressApp/node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (/path/to/expressApp/node_modules/bluebird/js/release/promise.js:691:18)
      at Async._drainQueue (/path/to/expressApp/node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (/path/to/expressApp/node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues (/path/to/expressApp/node_modules/bluebird/js/release/async.js:17:14)
      at Immediate.instrumented (/path/to/expressApp/node_modules/opbeat/lib/instrumentation/index.js:107:27)
      at tryOnImmediate (timers.js:543:15)
      at processImmediate [as _immediateCallback] (timers.js:523:5)
    
Opbeat logged error successfully at https://opbeat.com/<org>/<project>/errors/shortcut/<uuid> { uuid: '<uuid>' }
```

This error is successfully logged to opbeat, but the stack trace is not.
```
No data available.
```
Are we missing something ?

**Comment by watson** [comment]
@p-j It shouldn't be related to splitting it into modules

- Which version of the `opbeat` module are you using?
- Which version of Node are you running?
- Are you using babel, coffeescript or any other code compilation?
- Are you using any other error handler along with Opbeat (Rollbar, New Relic etc)?

**Comment by p-j** [comment]
Hi @watson 
We are running Node v6.5.0 and opbeat 4.0.0

The code is not transpiled: no coffee, no babel and on the error handler side here is what we have setup :

```javascript
// catch 404 and forward to error handler
app.use(middlewares.notFound)

// handled errors
// applicative errors, like validation errors
app.use(middlewares.clientErrors)

// opbeat monitoring
app.use(opbeat.middleware.express())

// error handler
// no stacktraces leaked to user unless in development environment
app.use(middlewares.errors)
```

**Comment by p-j** [comment]
To be more clear, it worked well when running opbeat 3.20.
When we split the code we upgraded opbeat at the same time to 4.0.

**Comment by watson** [comment]
@p-j thanks for the details 😃 Please email support@opbeat.com with a link to an error that have this problem, then I'll be happy to take a look

**Comment by p-j** [comment]
Hey, 

I had some time to dig on the issue today (finally...) and so I've followed the @watson trail :mag_right: : 
from [opbeat/opbeat-node/lib/middleware/connect.js#L6](https://github.com/opbeat/opbeat-node/blob/master/lib/middleware/connect.js#L6)
to [watson/stackman/index.js#L60](https://github.com/watson/stackman/blob/master/index.js#L60)
and then to [watson/error-callsites/index.js#L19](https://github.com/watson/error-callsites/blob/master/index.js#L19)

From here on, what could possibly go wrong ? 
You wraps `Error.prepareStackTrace` and all seems fine so why would my `__error_callsites` be undefined ?

Well... What if `Error.prepareStackTrace` is not what we expect it to be ? What if someone, somewhere, had redefined it ?

Well, in our dependency tree, we do have [jashkenas/coffeescript](https://github.com/jashkenas/coffeescript)

But unfortunately not the latest version that [removed the error prone prepareStackTrace](https://github.com/jashkenas/coffeescript/blob/d0ed2dee609313ae9c0668914c5ea0faf92e3889/documentation/sections/changelog.md#change-log) but [this version](https://github.com/jashkenas/coffeescript/blob/f26d33d418dcdcfcc6ad3ab774d9cabbf7af659c/lib/coffee-script/coffee-script.js#L347) that overwrite completely the `Error.prepareStackTrace`.

This explains the obvious *why?*, but the thing is: we have another project with the same dependency, that do not have this issue. And that is a mystery to me.

I haven't gone further in the investigation, and the solution, besides having (or forking) [deppie](https://github.com/Gaafar/deppie/blob/master/package.json#L26) upgrade it's version of [madge](https://github.com/pahen/madge) inorder to get rid of the dependency on `coffee-script` is unclear to me.

**Comment by watson** [comment]
@p-j Great work with the analysis of the issue 😃

The reason you see different results in your two projects could be related to the ordering of when the coffeescript module and the opbeat module gets a chance to overwrite `Error.prepareStackTrace`.

As far as I can see, the coffeescript module doesn't play nice and call the original value of `Error.prepareStackTrace` if there is one (e.g. opbeat). So if they are the last to overwrite `Error.prepareStackTrace` then the opbeat version of `Error.prepareStackTrace` will never get called.

On the other hand, in the error-callsites module, I carefully [keep a reference](https://github.com/watson/error-callsites/blob/9dcb172b2bf7c075b4fe1a30014205229a82b157/index.js#L5) to the original value of `Error.prepareStackTrace` and [call that](https://github.com/watson/error-callsites/blob/9dcb172b2bf7c075b4fe1a30014205229a82b157/index.js#L14) if it's set. So in the case of coffeescript that would mean that I called the coffeescript version of `Error.prepareStackTrace` and everything would be ok.

This would be a likely explanation at least. Could you check if the ordering of when the two pieces of code are run is different between the app where you get stack traces and the app where you don't?

**Comment by p-j** [comment]
I went through our initialization process and it appears indeed that we require `opbeat` as the very first package in the project where it doesn't work, whereas on the other one, `opbeat` is required after other dependencies. The fact that it works seems to be more linked to a favorable race condition or a lucky mistake more than anything else.

Do you see any downside at requiring / initializing opbeat not as the very first require like the doc says, but as the last one before any application code ?
I understand we wouldn't log errors crashing the server before opbeat is started but that's something I can leave without. Is there anything else ?

**Comment by watson** [comment]
For errors, if opbeat is required after the http module, you loose the ability to see which HTTP request caused a given error.

For general instrumentation, we maintain [a list of modules](https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#compatibility) here that we instrument. If any of those modules are required before opbeat is required, then we can't instrument that particular module.

So if you don't require a module on this list and those you do require doesn't directly or indirectly require any modules on this list, then there's no other downside than the missed exception you mentioned.

**Comment by p-j** [comment]
:+1: 
Ok, I'll have a look, while at the same time investigate ways to fix `deppie`.

**Comment by p-j** [comment]
Applied a dirty fix for now: use the cache of `require` 
make sure `deppie` is required first, then require `opbeat` right after. All subsequent `require('deppie')` call will hit the cache and opbeat gets to overwrite `prepareStackTrace` last.
It's not ideal, but it gets the job done for now.

Thanks for your help @watson :+1:
