### ISSUE TITLE
No route information when using Hapi with Glue

### ISSUE THREAD

**Issue by robinvdvleuten** [opbeat/opbeat-node#113]
Hi there,

I am using [Glue](https://github.com/hapijs/glue) to compose my Hapi server instance, but somehow no route information is displayed this way :(

**Comment by d3viant0ne** [comment]
Glad it's not just me.  

hapi: 16.1.0
glue: 4.1.0
opbeat: 4.4.0

![screen shot 2016-12-31 at 10 59 26 pm](https://cloud.githubusercontent.com/assets/8420490/21580252/0bba2ba4-cfad-11e6-934b-fa41de9defb8.png)

**Comment by AdriVanHoudt** [comment]
are you requiring opbeat before composing? I don't see a direct reason glue would mess with opbeat

**Comment by d3viant0ne** [comment]
@AdriVanHoudt I've tried it in both my `index.js` as well as my `prod.config.js` both of which are imported before the server composition. See below.

```
'use strict';

import Glue from 'glue';
import Chalk from 'chalk';
import Path from 'path';
import Labbable from 'labbable';
import Config from './config';

const ServerConfig = Config.server['jtx-node-server'];

const opbeat = require('opbeat').start({ // eslint-disable-line no-unused-vars
  appId: '',
  organizationId: '',
  secretToken: ''
});

ServerConfig.uri = (ServerConfig.tls
  ? 'https://'
  : 'http://') + `${ServerConfig.host}:${ServerConfig.port}`;

/**
 * Server Glue Plugin Manifest
 */
const manifest = {
  server: {
    app: Config
  },

  connections: [
    {
      host: ServerConfig.host,
      port: ServerConfig.port
    }
  ],

  // Registrations for global plugins only
  registrations: [
    {
      plugin: {
        register: 'hapi-auth-bearer-token'
      }
    }, {
      plugin: {
        register: 'hapi-auth-jwt'
      }
    }, {
      plugin: {
        register: 'good',
        options: Config.good
      }
    }, {
      plugin: {
        register: 'chairo',
        options: Config.chairo
      }
    }, {
      plugin: {
        register: 'inert'
      }
    }, {
      plugin: {
        register: 'vision'
      }
    }, {
      plugin: {
        register: 'hapi-swagger',
        options: Config.swagger
      }
    }, {
      plugin: {
        register: 'dogwater',
        options: Config.dogwater
      }
    }, {
      plugin: {
        register: '../lib'
      }
    }
  ]
};

/**
 * In Memory Cache Configuration
 */
if (Config.cache) {
  const caches = [];
  Object.keys(Config.cache).forEach((key) => {
    caches.push(Config.cache[key]);
  });
  manifest.server.cache = caches;
}

/**
 * Instantiates Labbable for testing
 */
const labbable = module.exports = new Labbable();

const opts = {
  relativeTo: Path.join(__dirname, 'node_modules')
};

/**
 * Compose and Initialize Hapi Server
 */
Glue.compose(manifest, opts, (err, server) => {
  if (err) {
    throw err;
  }

  labbable.using(server);

  const bootMessage = `

   ${Chalk.magenta.underline('JobTrak Server Initialized!')}\n
    - ${Chalk.blue(Config.product.name + ' is listening on')} ${Chalk.white.underline(ServerConfig.uri)}\n
    - ${Chalk.blue('Swagger Documentation at ')} ${Chalk.white.underline(ServerConfig.uri + '/docs')}\n
    - ${Chalk.red('Environment: ' + Config.env)}\n
  `;

  server.initialize((err) => {
    if (err) {
      throw err;
    }

    if (Config.auth) {
      server.auth.default(Config.auth);
    }

    server.start((err) => {
      if (err) {
        throw err;
      }
      setTimeout(() => {
        console.log(bootMessage);
      }, 2000);
    });
  });
});
```

**Comment by watson** [comment]
@d3viant0ne you need to call the `start()` function on the Opbeat agent before importing/requiring anything. If not, Opbeat will not have a chance to hook into Hapi. E.g:

```js
'use strict';

const opbeat = require('opbeat').start();

import Glue from 'glue';
import Chalk from 'chalk';
import Path from 'path';
import Labbable from 'labbable';
import Config from './config';
```

@robinvdvleuten Can this be your issue as well?

**Comment by robinvdvleuten** [comment]
@watson I do have opbeat as first line of the application's entrypoint

**Comment by robinvdvleuten** [comment]
I can try to create a sandbox app with the issue later

**Comment by watson** [comment]
@robinvdvleuten thanks, that would be really helpful :)

**Comment by d3viant0ne** [comment]
In the end, you just have to get it imported before glue.

I was able to keep it in my prod config & then move the config imports above glue. The snippet below is posting routes as one would expect and limits opbeat to anything running in a `production` env.

```
'use strict';

import Config from './config';
const ServerConfig = Config.server['jtx-node-server'];

import Chalk from 'chalk';
import Glue from 'glue';
import Labbable from 'labbable';
import Path from 'path';
```

**Comment by watson** [comment]
@d3viant0ne as long as your `./config` file isn't requiring (directly or indirectly) any of the modules listed in [the `MODULES` array](https://github.com/opbeat/opbeat-node/blob/f25426a83c8baefdcd6f816eef4a6328a2846df1/lib/instrumentation/index.js#L11), then it's fine. Then you could even move Opbeat outside of your config module again and have it just below the `import Config from './config';` line if you like.

Opbeat just needs to be required and started before any of those modules listed in the `MODULES` array are required.

**Comment by d3viant0ne** [comment]
No, it's just environment specific configuration values exported as a module, works like a charm :)

![screen shot 2017-01-02 at 7 40 57 am](https://cloud.githubusercontent.com/assets/8420490/21590183/0e0e544e-d0bf-11e6-878d-d4ee80774044.png)

**Comment by Arcrueid** [comment]
same problem with hapi 17.1.1

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

I'm sorry that you encountered this error. Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. Large parts of the source code have been rewritten since then, so the bug might have been fixed there already. If you're interested in trying out Elastic APM, we'd love your [feedback](https://discuss.elastic.co/c/apm).
