### ISSUE TITLE
Call .start() more than once

### ISSUE THREAD

**Issue by jsmrcaga** [opbeat/opbeat-node#133]
I guess I;m not the only one with this issue, so I'll post it here.

I was wondering if there is a workaround the error thrown when calling the agent more than once. As a matter of fact, I have a framework (which uses opbeat) and an app on top of the framework (which uses opbeat). I have a module like so:
```javascript
const opbeat = require('opbeat').start({... <framework settings>});
const opbeat_local = require('opbeat').start({...<local app settings>});
```
The idea is to get performance metrics for the app while logging errors on the framework opbeat app.

I understand why starting an agent twice with the same keys would be a problem however.

**Comment by watson** [comment]
Thanks for opening the isssue.

The Opbeat agent is a singleton object. It hooks into Node-core and 3rd party modules in several locations, so starting it more than once will add the hooks twice which isn't supported. There's also an issue with handling of uncaught exceptions where two instances of the agent would step on each others toes.

So right now there's no workaround for this.

But I'd love to understand your use-case better. Can you explain it in more details?

**Comment by jsmrcaga** [comment]
Thanks for the quick answer. I just forked the repo to check it out, and if there are many one-way hooks sadly it won't be possible as you say.

My use case is as follows:
We have a framework on top of which we build many different applications. The idea is to have a `framework` app declared in Opbeat, as well as `myApp#X`. The module would then log errors to `framework` (using `{instrument:false}`) and would log performance metrics to `myApp#X` .
That means starting the module twice with different app_key / secret.

**Comment by watson** [comment]
In that scenario, how would you like to handle uncaught exceptions?

**Comment by jsmrcaga** [comment]
Uncaught exceptions would be logged to both applications, but it would still centralize the errors on the `framework` app.

**Comment by watson** [comment]
To hack this, you'd have to get two instances of the [`Agent`](https://opbeat.com/docs/articles/nodejs-agent-api/#agent-api). It's easiest if you just let one of the agents handle exceptions though.

Here's a raw example - not tested, and it might have bugs or drawbacks that I haven't thought of:

```js
var Agent = require('opbeat/lib/agent')

var opbeat = new Agent()
var opbeat_local = new Agent()

opbeat.start({instrument: false, ...})
global.__opbeat_initialized = false // hack to allow to start Opbeat more than once
opbeat_local.start({captureExceptions: false, ...})
```

The drawback of disabling instrumentation on one of the agents, is that errors captured by that agent will not have a reference to the active HTTP request.

**Comment by jsmrcaga** [comment]
Ok great!
I'll test it this afternoon or tomorrow and let you know!

**Comment by watson** [comment]
Bear in mind that this is unsupported behaviour and might stop working in a patch update

**Comment by jsmrcaga** [comment]
@watson I've deployed a custom version where the `global.__opbeat_initialized` is treated as usual, but it adds a `global.__opbeat_agents = []` that keeps track of all agents started. It stores keys as `hex(appId + orgId + secret)`. It can then check if an identical agent is being intanciated and throw an error.

It's been working as expected for the last hour, logging errors to the `framework` app (sadly and happily no errors yet, so can't really verify) and logging performance to the given app. I'll keep you posted, but i wanted to know: do you prefer if i made  a pull request (it passed all tests and style guide) or if I `nmp publish` it with a name like `opbeat-multiagent` ?

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. If you're interested in trying out Elastic APM, we'd love your [feedback](https://discuss.elastic.co/c/apm).

We have not yet implemented this feature in the Elastic APM Node.js Agent, but if you like to bring it up again, you're welcome to open a [feature request](https://github.com/elastic/apm-agent-nodejs/issues/new?template=Feature_request.md).
