### ISSUE TITLE
Add better fallback for `undefined undefined` errors

### ISSUE THREAD

**Issue by watson** [opbeat/opbeat-node#14]
Some errors are logged in Opbeat as `undefined undefined`. This happens when the regular error message extractor fails extracting any meaningful error message. In those cases we should add a better fallback - optionally just the same fallback as the built-in V8 stack trace generator uses.

**Comment by watson** [comment]
I think I was wrong about the reason for this error. It should now be fixed in v1.1.1

**Comment by Neamar** [comment]
Ok, will test this. Thanks!

**Comment by watson** [comment]
@Neamar Allow me to give a little background info:

I was able to reproduce this by trying to capture an error which wasn't an error, e.g. `opbeat.captureError({ foo: 1 })`.

It happened to my self while using express/connect and adding an error handler to the middleware stack. Apparently - at some place in my app - I parse a non-error object as the first argument to a callback which then gets picked up by the connect error handler and logged to Opbeat. Since it's not a real error object, the Opbeat client previously tried to extract the "obj.message" property but failed in a way that resultet in the string "undefined undefined" being logged instead.

**Comment by Neamar** [comment]
Ok, good to know -- this is probably what's happening in our case too. I guess we'll see what's happening soon ;)

**Comment by watson** [comment]
@Neamar as you might have seen in the new agent source code, we now log the output of `util.inspect(obj)` instead of "undefined undefined". This way you might be able to track down where in your code you send the bad error object
