### ISSUE TITLE
Set global context for errors outside the scope of a transaction

### ISSUE THREAD

**Issue by garrylachman** [opbeat/opbeat-node#141]
How can i add extra data to handleUncaughtExceptions ?
i want to add the package version and user id but its not working for handleUncaughtExceptions

**Comment by watson** [comment]
It should work the same as normal errors: You can normally use [`opbeat.setUserContext()`](https://opbeat.com/docs/articles/nodejs-agent-api/#opbeat-setusercontext) for the user id and [`opbeat.setExtraContext()`](https://opbeat.com/docs/articles/nodejs-agent-api/#opbeat-setextracontext) for the package version.

But there is one caveat: If there's no active transaction, the Opbeat agent will not have anything to bind the context to. Is that the issue in your case?

**Comment by garrylachman** [comment]
No active trans...
An option to set global context is the best option to solve this issue..

**Comment by watson** [comment]
You mentioned that you have a user id. Is that from a logged in user?

**Comment by garrylachman** [comment]
not just the user id.
i want to add the version, os version, os arch...

i not find the release tracker helpfull because not all the users update the application and i can't detect the specific version when the error logged, so i want to add the version to extra context.

**Comment by watson** [comment]
Makes sense. And I agree that it might make sense to have a way to set this extra context outside the scope of a transactions. But I'm just trying to understand your specific use case here: If we are talking about a regular HTTP based application and a user is making an HTTP request to the app, then there should be an active transaction during that request/response life-cycle. Is that correctly understood?

**Comment by garrylachman** [comment]
No...
Its standalone application that installed on user computer.

**Comment by watson** [comment]
Got ya 😃

I've updated the title to reflect that this is only an issue when there's no active transaction.

As I mentioned before there's unfortunately no proper solution for this at the moment.

**Comment by garrylachman** [comment]
its very easy to implement this, just add option to add "default extra context" and merge it with any transaction before send...

**Comment by watson** [comment]
Doh! I just realised that you of course can use the [`opbeat.addFilter()`](https://opbeat.com/docs/articles/nodejs-agent-api/#opbeat-addfilter) function to set a default extra context. It will then be called every time an error is about to be sent to Opbeat and for every transaction that's being logged as well:

```js
opbeat.addFilter(function (context) {
  // set default extra context to ALL errors and transactions
  if (!context.extra) context.extra = {}
  context.extra.foo = 'bar'

  // remember to return the modified context
  return context
})
```

I don't know why I didn't think of that before 😬 Does this satisfy your requirements?

**Comment by jetstarmedia** [comment]
Great... working perfect
