### ISSUE TITLE
Make the console.log message of reporting an error silent

### ISSUE THREAD

**Issue by jbavari** [opbeat/opbeat-node#15]
First off, thanks for providing an awesome error logging solution. We've been using it for a few weeks now, and it's pretty solid.

I'm not sure if there is an option and I overlooked it, I'm looking for a way to silent the `console.log` messages from reporting errors.

We are using this as an open source project command line interface from a project, Ionic. 

Since we have a plethora of users from around the world using the CLI, we'd like to not show the users the link to the opbeat errors.

Is there any way to silent the message that comes when an error is reported? 

The message in question is:
`Opbeat logged error successfully at https://opbeat.com`

I've found in `index.js` - line 60 and line 145, there is a callback from captureError that then `console.log`s the message out.

```
      if (opbeatErr) {
        client.logger.info('Could not notify Opbeat!');
        client.logger.error(opbeatErr.stack);
      } else {
        client.logger.info('Opbeat logged error successfully at ' + url);
      }
```

Would there be any way to disable or silence this logging? I'd really appreciate any feedback or suggestions you have to offer!

Thanks in advance.

**Comment by watson** [comment]
@jbavari you can use the [`clientLogLevel`](https://github.com/opbeat/opbeat-node#clientloglevel) option to silence the part of the output you do not want.

For instance, if you do not want info messages to be outputtet, you can change the log level from `info` (default) to `warn`:

```js
require('opbeat')({
  clientLogLevel: 'warn',
  // your other settings go here...
});
```

This will still output warnings and errors, which means that stack traces captured by Opbeat will still be outputtet. If you would not like those to be outputted either, you can raise the log level even more.

Does this solve your problem?

**Comment by jbavari** [comment]
Yes, thanks! I made a mistake and overlooked this. Awesome library.
