### ISSUE TITLE
Module breaks sending Errors through express

### ISSUE THREAD

**Issue by JetFault** [opbeat/opbeat-node#19]
I am using Sails.js (built ontop of Express) and created my own ApiError object that I send to the client side using `res.json`. Before putting in this module everything worked fine. After adding it, it seems like stackman is adding a Circular JSON object onto every single Error object created after the first `opbeat.captureError` call. 

The additional property that gets added to all Error objects is `_sb_callsites: Array[9]` which went sent through res.json throws this error: `Unhandled rejection TypeError: Converting circular structure to JSON`

**Comment by roncohen** [comment]
@JetFault hey! Thanks for reaching out and sorry for the slow response. Is this still an issue?

**Comment by watson** [comment]
@JetFault I'm closing this one now. But feel free to reopen the issue if you still have the problem :smiley:
