### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by AdriVanHoudt** [opbeat/opbeat-node#199]
The next version of hapijs (v17) will be async/await only. Is this supported by this tracing module?

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. If you're interested in trying out Elastic APM, we'd love your [feedback](https://discuss.elastic.co/c/apm).
