### ISSUE TITLE
Could you please create stream for bunyan logger?

### ISSUE THREAD

**Issue by DenisIzmaylov** [opbeat/opbeat-node#21]
I would like to use bunyan logger. I found [bunyan-loggly](https://github.com/smebberson/bunyan-loggly) but I did not found yet the same solution for opbeat. Could you please create it?

**Comment by watson** [comment]
@DenisIzmaylov Do you mean when the bunyan log level is `error` or `fatal` that you would then like to log those to Opbeat?

**Comment by watson** [comment]
@DenisIzmaylov I'm closing this one now. But feel free to reopen if this is still a request :smiley:

**Comment by mderazon** [comment]
@watson I have create a Bunyan stream for Opbeat here: https://github.com/mderazon/bunyan-opbeat/blob/master/lib/index.js

It's still very initial, but I am trying to figure out some stuff with Opbeat module.

Looking at this doc: https://opbeat.com/docs/api/intake/v1/#-error-logging- , I am trying to understand what fields Opbeat module already sends out to the api and what fields I better add separately. 

Does Opbeat module sends `stacktrace` / `exception` / `http` fields ? Or should I include them ? And if I should include, i'm not sure there's an easy way to translate the Error stacktrace to the format you expect.

Also, looking at `culprit`, I can ask Bunyan for a source (https://github.com/trentm/node-bunyan#src) but Bunyan docs clearly states that this shouldn't be done in production as the performance is bad. How do Opbeat module handles source line / function name ?

Thanks,
Michael

**Comment by watson** [comment]
@mderazon great work with the bunyan logger 😃 

I'm not sure if I understand your question correctly, but I'll do my best to answer below. Feel free to clarify, if I got it wrong.

The opbeat agent will automatically make sure to send all the fields required and even add a few extra goodies like the current Node.js version etc. So you shouldn't need set `stacktrace`, `exception` etc. yourself.

As a result you can use `opbeat.captureError(err)` without any options if you like. The Intake API docs that you link to, is mostly used if you want to build a custom agent your self. If you're interested in the API docs for the agent, I'd instead recommend the [Opbeat Node.js Agent API docs](https://opbeat.com/docs/articles/opbeat-for-nodejs-api/).

For details of how you can add extra info the captured error, check out the [`opbeat.captureError()` docs](https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#captureerror).

Does that make sense?

**Comment by mderazon** [comment]
Thanks, looks good.

One last thing is about the `culprit`. In the tests I've done I see that it's not populated automatically.  Shouldn't it be taken from the Error as well ?

**Comment by watson** [comment]
@mderazon Normally yes. But if it for some reason could not get access to thte stack trace it can't set it. Or if you set it manually, we'll of cause use that instead of the one from the error. Can you show me the test that's failing?

**Comment by mderazon** [comment]
It's not a proper test, more like experiment. I have invoked captureError(Error) and looked at the dashboard. I see the complete stack trace but in culprit it says `No culprit available`. 

I have published the module for bunyan btw for anyone interested:
https://www.npmjs.com/package/bunyan-opbeat

I will try investigating this again and follow up

**Comment by watson** [comment]
@mderazon please email us at support@opbeat.com or send us a message using the "Help" button when logged in to opbeat.com. Then I can have a look at the error to see why there's no culprit.

...and congrats on publishing! :shipit:
