### ISSUE TITLE
Transaction is out of sync.

### ISSUE THREAD

**Issue by iCyberon** [opbeat/opbeat-node#22]
Hey there,

I've just tried the 2.0 version and I see "Transaction is out of sync." and "Can't record ended trace after parent transaction have ended - ignoring!" messages. I'm using Sails.js which is based on express. 

Am I doing something wrong or it's the debug info? Also, one more question regarding the usage. Before 2.0 I was able to initialize more than one instance. I used one in middleware and another one for logging. As I see I cannot do that anymore, is there any way to get already initialized instance?

**Comment by iCyberon** [comment]
Looks like it might be related to socket requests. @watson How does opbeat handles socket requests?

**Comment by watson** [comment]
@iCyberon Thanks for reporting this issue.

The agent currently doesn't support web sockets. We're working on an API that allows you to tell the agent when a transaction starts and when it stops. That will allow you to manually trace web socket connections.

That being said, I will look into Sails.js to see if there is something we can do automatically.

**Comment by iCyberon** [comment]
Thanks, looking forward for changes. If there's anything I can do to make the development faster let me know ;)

**Comment by watson** [comment]
@iCyberon I'm just doing a little house keeping of the issues on this repo and I noticed that I never answered your second question about how to retrieve the existing agent:

As you might have already discovered you can now call `require('opbeat')` multiple times and it will always return the same agent. So there is no need to manually share an instance of the agent between different parts of your code. The only thing you need to take care of is calling the `.start()` function once at the very top of your main app file.

Regarding web sockets, expect documentation on this to be there soon :smiley:

**Comment by iCyberon** [comment]
@watson Yeah, already discovered that. Thank you :+1: Does that mean we'll soon be able to track socket activity? :boom:

**Comment by watson** [comment]
@iCyberon yes, but you'll need need to help us out a little bit since we can't know when a transaction starts and when a transaction ends - so there'll be a way to start and end transactions.

**Comment by watson** [comment]
@iCyberon we just fixed a bug that could cause out of sync transactions in some use-cases. It's released on npm as v3.5.1. Please give it a spin and let me know if it fixes the issue.

**Comment by watson** [comment]
@iCyberon I'm going to close this issue for now. If you still experience the problem after upgrading, feel free to reopen it :smiley:
