### ISSUE TITLE
How is the progress of support Restify?

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [opbeat/opbeat-node#227]
Hello, I noticed that there is no documentation for Restify but there is a discourse in #33 

Is there any code for this being produced?

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated, so I'll close this issue.

Restify support was never added to the Opbeat agent though, but if you're interested in trying out [Elastic APM](https://www.elastic.co/solutions/apm), we'll be happy to add support for it there.

Step one is to create a [feature request](https://github.com/elastic/apm-agent-nodejs/issues/new?template=Feature_request.md) in the [Elastic APM Node.js agent](https://github.com/elastic/apm-agent-nodejs) repo.
