### ISSUE TITLE
express Router route recognition

### ISSUE THREAD

**Issue by mderazon** [opbeat/opbeat-node#28]
I am using [express.Router](http://expressjs.com/en/api.html#router) for nested routes i.e.
main `app.js`:
``` js
var express = require('express')
var users = require('./users')

var app = express() // main app
// ...
app.use('/users', users)
```
and in `users.js`:
``` js
var express = require('express')

var router = express.Router()

router.get('/', function(req, res, next) {
// ...
})

module.exports = router
```

It seems that Opbeat doesn't recognize the nested routes correctly and shows them as unknonwn.

**Comment by watson** [comment]
@mderazon Thanks for letting us know about this issue. I'm working on getting it fixed in the next release

**Comment by dizballanze** [comment]
:+1:

**Comment by mderazon** [comment]
@watson just checked and this seems to be fixed now, am I right ?

**Comment by watson** [comment]
@mderazon Yes, indeed it is :ship: - Forgot to notify and close this issue. Thanks for letting us know :smiley: 

The time measured is as perceived from the users point of view - e.g. from the HTTP request is received by the Node HTTP server till it emits a `finish` event. In regards to grouping, we name and group the request based on the first matching route. So if you yourself call `next` from the matching endpoint to have it "fall through" and continue the matching, it will be named and grouped under that first matching endpoint.

Does that answer your question? If I have misunderstood you, can you maybe show me a simple code snippet of what you mean with that it "goes through `/users`"?

**Comment by mderazon** [comment]
It does answer some questions.
By mathcing you mean `app.use` matches as well ? Or only explicit verbs ? (GET / POST etc)
Because I have the project set up so that any request to `/users/orders` go through `/users` middleware, so `orders` middleware is "nested" under `users` one (with basically calling app.use on express.Router)

```
├── user
    └── orders
```

(The approach i'm talking about is described in the following video by tjholowaychuk https://vimeo.com/56166857)

**Comment by watson** [comment]
@mderazon Only explicit verbs count. So you should be able to mount an app or an instance `express.Router` using `app.use`

**Comment by andersryanc** [comment]
I have a somewhat related issue in my app. I'm also using `express.router` for nested routes and then load them into express with:

```js
const app = express();
// ...
import customers from './routes/customers';
import books from './routes/books';
// ...
app.use('/customers', customers);
app.use('/books', books);
// ...
```

but opbeat is showing them in the "Performance" page as just `GET /` and `POST /:id`. This is somewhat annoying since I have multiple nested routes using similar URIs... I would have expected them to show up in the "Performance" page as `GET /customers` and `POST /customers/:id` and then `GET /books` and `POST /books/:id`, etc.

**Comment by watson** [comment]
@andersryanc It should work just fine.

- Which version of Express are you using?
- Which version of the Opbeat agent are you using?
- Do you mind share either the customer or books routes definitions with us?

**Comment by andersryanc** [comment]
yarn.lock
```
// ...

express@^4.13.4:
  version "4.15.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.15.2.tgz#af107fc148504457f2dca9a6f2571d7129b97b35"

// ...

opbeat-http-client@^1.0.3, opbeat-http-client@^1.2.2:
  version "1.2.2"
  resolved "https://registry.yarnpkg.com/opbeat-http-client/-/opbeat-http-client-1.2.2.tgz#8ad399969d508254dace2d0853981368117da33f"

opbeat-release-tracker@^1.1.1:
  version "1.1.1"
  resolved "https://registry.yarnpkg.com/opbeat-release-tracker/-/opbeat-release-tracker-1.1.1.tgz#2f65767250b955ae988edca875acd836120e7e0a"

opbeat@^4.13.1:
  version "4.13.1"
  resolved "https://registry.yarnpkg.com/opbeat/-/opbeat-4.13.1.tgz#77dbdb50496eb9f34380870c7bbe3a9b18d7d5ca"

// ...
```

server.js
```js
import _ from './env';
if ( !process.env.NODE_ENV ) {
  process.env.NODE_ENV = 'production';
}

const opbeat = require('opbeat').start({
  appId: '',
  organizationId: '',
  secretToken: ''
});

import fs from 'fs';
import path from 'path';
import glob from 'glob';
import express from 'express';
import compression from 'compression';
import bodyParser from 'body-parser';
import errorHandler from 'errorhandler';
import morgan from 'morgan';
import validator from 'express-validator';
import helmet from 'helmet';
import cors from 'cors';
import { httpResponseCodes, messages } from './config';

require('./lib/cron');

const app = express();

var expressLogFile = fs.createWriteStream(__dirname + '/logs/express.log', {flags: 'a'});
app.use(morgan('combined', { stream: expressLogFile }));

import { requireHttps } from './middleware';
app.use(requireHttps);

app.use(cors({
  origin: [
    /(localhost)/,
    process.env.API_ORIGIN,
  ],
}));

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.use(validator({}));

app.use(compression());
app.use(express.static(__dirname + '/static', {
  setHeaders: (res) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  }
}));

import { renderEmail } from './lib/mail';
app.use('/emails/render/:name', (req, res) => {
  const emailName = req.params.name.replace('-', '/');

  const emailPath = path.join(__dirname, './emails/', emailName + '.mustache');
  if ( !fs.existsSync(emailPath) ) { return res.send('NOT FOUND'); }

  const tmpl = renderEmail(emailName, {
    firstname: 'Joe',
    lastname: 'Sample',
    emailaddress: 'joe@sample.com',
  });
  res.send(tmpl);
});

app.use(helmet());
app.use((req, res, next) => {
  res.removeHeader('Connection');
  next();
});
app.set('json spaces', 2);

import auth from './routes/auth';
import applications from './routes/applications';
import customers from './routes/customers';
import customer from './routes/customer';
import geocode from './routes/geocode';
import install from './routes/install';
import offers from './routes/offers';
app.use('/auth', auth);
app.use('/applications', applications);
app.use('/customers', customers);
app.use('/customer', customer);
app.use('/geocode', geocode);
app.use('/install', install);
app.use('/offers', offers);

app.use('*', (req, res) => {
  res.status(httpResponseCodes.NOT_FOUND).send({ message: messages.NOT_FOUND });
});

if ( process.env.NODE_ENV !== 'development' ) {
  app.use(opbeat.middleware.express())
} else {
  app.use(errorHandler({ dumpExceptions: true, showStack: true }));
}

export default app;
```

routes/customer.js
```js
import express from 'express';
import pass from 'pwd';
import { checkApiToken, checkTrackingLinks } from '../middleware';
import { log, query } from '../lib';
import uuid from 'uuid/v4';
import { httpResponseCodes, messages } from '../config';
import Customer, { validation as customerValidation } from '../models/customer';
import Authentication from '../models/authentication';
import { login } from '../lib/auth';
import { renderEmail, sendEmail } from '../lib/mail';
const router = express.Router();

const resource = 'Customer';

const validateCustomersRequest = (req, res, next) => {
  // ...
}

const checkForExistingCustomer = (req, res, next) => {
  // ...
}

const hashPasswordIfSet = (req, res, next) => {
  // ...
}

router.post('/', validateCustomersRequest, checkForExistingCustomer, checkTrackingLinks, hashPasswordIfSet, (req, res) => {
  const { device, location } = req.body;

  delete req.body.password;
  new Customer(req.body).save((err, customer) => {
    if (err) {
      return res.status(httpResponseCodes.ERROR).send({ message: messages.MODEL_ERROR });
    }

    if ( req.pass ) {
      const { salt, hash } = req.pass;
      new Authentication({ auth_token: uuid(), customer_id: customer.id, password_hash: hash, password_salt: salt }).save();
    }

    login(customer.id, { location, device }).then(
      loginRes => {
        const isIncomplete = customer.isIncomplete();

        let responseData = {
          id: customer.id,
          customer_id: customer.id,
          token: loginRes.token,
          incomplete: isIncomplete,
          scheduledApplicationId: null,
          firstname: customer.firstname,
          lastname: customer.lastname,
          city: customer.city,
          state: customer.state,
          zip: customer.zip,
        };

        res.send(responseData)
      },
      loginErr => res.status(loginErr.status).send(loginErr)
    );
  });
});

export default router;
```

**Comment by watson** [comment]
@andersryanc I tried to run your code (stubbing out the local files that you didn't provide) and it all worked as expected.

I did however find one issue: I imagine you are using Babel? In that case your posted code will not work because the `import` statements will be hoisted above the call the `opbeat.start()`.

If you want to use Opbeat with Babel you have to import the `opbeat/start` script and then you can't supply the configuration inline.

Instead you can supply the config options via either environment variables or via a local config file. See the two first sections in the API docs for details: https://opbeat.com/docs/articles/nodejs-agent-api/

**Comment by andersryanc** [comment]
Thanks @watson! That was it. I was reading through the express docs: https://opbeat.com/docs/articles/get-started-with-express/

Might be nice to add in that little blue box about babel on the page you sent me to the express docs as well.

**Comment by watson** [comment]
@andersryanc Good point. I'll make sure we do that. I'm still a little curious why the issue you saw was related to using Babel. In that case you should simply not have seen any transactions at all. Weird, but glad it worked 😃
