### ISSUE TITLE
Could not notify opbeat

### ISSUE THREAD

**Issue by iCyberon** [opbeat/opbeat-node#29]
Hey guys, I'm having an issue. 

```
backend-1 (err): Could not notify Opbeat { uuid: undefined }
backend-1 (err): Error: connect ETIMEDOUT 54.86.238.45:443
backend-1 (err):     at Object.exports._errnoException (util.js:874:11)
backend-1 (err):     at exports._exceptionWithHostPort (util.js:897:20)
backend-1 (err):     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

Looks like some kind of network issue.

**Comment by watson** [comment]
@iCyberon Everything looks ok on our end and the IP in your stacktrace is correct. Is the issue persistent?

**Comment by iCyberon** [comment]
Unfortunately yes, though I think it's not directly related to opbeat. It happens when CPU is near 100%.

**Comment by watson** [comment]
@iCyberon I'll close this issue for now. Please feel free to reopen if you think it's related to Opbeat after all :smiley:
