### ISSUE TITLE
Error: Cannot find module 'stack-trace'

### ISSUE THREAD

**Issue by MrDHat** [opbeat/opbeat-node#30]
Stacktrace in the image

![opbeatstacktrace](https://cloud.githubusercontent.com/assets/1485255/12223732/b7fb838e-b804-11e5-90ad-916cb6189ce8.png)

**Comment by watson** [comment]
@MrDHat I don't think this error is related to the Opbeat agent. It seems that your app (or more accurately a dependency of your app) is trying to require the `stack-trace` module but that it's not able tot find it. You should verify that you've installed it on your server and/or that it's added as a dependency in your package.json file.

**Comment by MrDHat** [comment]
@watson Oh, right. I confused opbeat with another reporting service I was using. Really sorry for this. Closing now.
