### ISSUE TITLE
Feedback: GET unknown route

### ISSUE THREAD

**Issue by mhaamann** [opbeat/opbeat-node#31]
Using express 4.12.4 we were seeing a lot of hits identified by 'unknown route'. We traced this to being static files such as images which were being served using express.static.

We got around this by using the following middleware function:
```
function opbeatStaticFileServing(name) {
  return function (req, res, next) {
    opbeat.setTransactionName('static:' + name);
    return next();
  };
}
```

Might help someone in the future.

**Comment by watson** [comment]
@mhaamann Thanks for the tip :smiley: We're working on making the agent detect static routes automatically, so you don't have to resort these sort of patches in the future.

**Comment by watson** [comment]
@mhaamann this have now been automated and released on npm as v3.2.0 :smiley: 

Static files are now grouped into one of two transactions:

- `GET static file`
- `HEAD static file`

**Comment by mhaamann** [comment]
great! Thanks for the heads up.

**Comment by AdriVanHoudt** [comment]
is it possible this is also happening with Hapi?

**Comment by captainjackrana** [comment]
I'm getting the **Unknown Routes** listed on my Hapi Server. Does anybody know what it refers to?
<img width="922" alt="screen shot 2016-10-20 at 10 16 10 pm" src="https://cloud.githubusercontent.com/assets/5394402/19569294/db792bac-9712-11e6-9340-f2a85db665f8.png">

**Comment by watson** [comment]
@captainjackrana if you click the `GET unknown route` link, check if the "Requests per minute" graph mainly show `4xx` requests. In that case this is most likely 404 HTTP requests where there isn't any route for it to match

**Comment by captainjackrana** [comment]
@watson But how do i figure out what was the route requested? How can i debug this scenario

**Comment by watson** [comment]
@captainjackrana if you're running the latest 3.x or 4.x version of the Opbeat agent, and you click on the `unknown route` link and scroll down to the trace breakdown, you'll see an info tap. Click that and it will show you a sample request with the full URL for the request
