### ISSUE TITLE
Hapi uncaught errors

### ISSUE THREAD

**Issue by ndreckshage** [opbeat/opbeat-node#32]
Hapi catches exceptions (https://github.com/hapijs/hapi/blob/a7b3ad753febbacc10e17e352de6385dfc642dca/lib/protect.js#L43), so errors dont make it to opbeats uncaught error listeners (https://github.com/opbeat/opbeat-node/blob/c3f8e9ed07c2cd34bf17115fe1ea7890ed6f2c91/lib/agent.js#L210). User can hook into Hapi's ```server.on('request-error')``` event and send to opbeat manually.

Not a bug with opbeat, but might be a worthy addition to the readme, etc, as Hapi is one of the most popular node frameworks.

**Comment by watson** [comment]
@ndreckshage thanks for letting us know about this. I think we could easily do this for you automatically. Will you say it would be expected behaviour for Opbeat to hook into `server.on('request-error')` automatically, or would you as a user expect to have to handle this yourself?

**Comment by ndreckshage** [comment]
If you can do this automatically (how? ```opbeat.configureHapi(myHapiInstance)```), I think it would be nice. But I think Hapi configuration details in https://github.com/opbeat/opbeat-node/wiki/Compatibility-Guide would also suffice. But automatically would be a lot easier for a micro service architecture with many node apps.

**Comment by watson** [comment]
Ok, thanks :smiley: Glad you mentioned configuration documentation. I'm currently working on guides to both Hapi and Express - you can see what I've made for Express so far [here](https://github.com/opbeat/opbeat-node/wiki/Get-started-with-Opbeat-for-Express) - We'll create something similar for Hapi

**Comment by AdriVanHoudt** [comment]
If you are open for a PR for this let me know

**Comment by pdufour** [comment]
Any progress on this?

**Comment by watson** [comment]
@pdufour Thanks for bumping this - You got me motivated to work on it over the weekend 😄 I'm close to having a solution 😃

**Comment by AdriVanHoudt** [comment]
@watson if you want to know how I do error logging with hapi atm let me know, would love to help out!

**Comment by watson** [comment]
@AdriVanHoudt @pdufour @ndreckshage I've created pull request #59 that addresses this issue. I'd love to hear your guys opinion on the solution proposed in the PR as you work with hapi on a daily basis. For instance, right now it's always on - but should it be possible to disable this feature?

**Comment by pdufour** [comment]
Nice work! Not sure it would need to be toggable. I think if you enable opbeat you would expect these errors to be logged.
