### ISSUE TITLE
Is it possible to use this with restify?

### ISSUE THREAD

**Issue by kenichi-shibata** [opbeat/opbeat-node#33]
How do I set up performance monitoring?

Sorry it seems like theres not documentation for this

**Comment by iCyberon** [comment]
@fr-kshibata It's done automatically. Once you call the ```start``` method agent will start monitoring. 

> By default, the Opbeat agent will track incoming HTTP requests and group them in transactions. During a transaction, the associated database queries, requests to external services etc. are measured along with the total transaction time. [[Readme]](https://github.com/opbeat/opbeat-node#instrumentation)

You can change this behavior by setting ```instrument``` parameter to ```false```. [[Options]](https://github.com/opbeat/opbeat-node#instrument)

**Comment by fr-kshibata** [comment]
```
var opbeat = require('opbeat').start({
  organizationId: '1111111',
  appId: '111111',
  secretToken: '11111',
  active: true,
  instrument: true
});
```
I have this code on the start on my main file before I start the restify server but its still not collecting performance metrics only errors

**Comment by fr-kshibata** [comment]
server is 
```
// im using bunyan logger
var restify          = require('restify');
var bunyan        = require('bunyan');
var log = bunyan.createLogger({
  name: 'project1',
  level: loggerCfg.logLevel,
  streams: loggerCfg.streams,
  serializers: bunyan.stdSerializers,
});

var server = restify.createServer({
  name: 'project1',
  log: log,
  formatters: {
    'application/json': function (req, res, body) {

      if (body instanceof Error) {
        log.error(body);
        return '';
      }

      res.setHeader('Connection', 'close');

      res.charSet('utf-8');
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Cache-control', 'max-age=0, private, must-revalidate');
      res.setHeader('Content-Type', 'application/json; charset=utf-8');

      return JSON.stringify(body);
    },
  },

});

server.use(restify.bodyParser({ mapParams: false }));
server.use(restify.queryParser());
server.use(restify.gzipResponse());
server.pre(restify.pre.sanitizePath());

server.use(restify.CORS());
server.use(restify.fullResponse());
```

**Comment by iCyberon** [comment]
@fr-kshibata I think Instrumentation works for Express and hapi only. 

/cc @watson

**Comment by fr-kshibata** [comment]
@iCyberon I see no support for restify for now?

**Comment by iCyberon** [comment]
@fr-kshibata Check the list of [supported modules](https://github.com/opbeat/opbeat-node/wiki/Application-Instrumentation#supported-modules).

**Comment by fr-kshibata** [comment]
@iCyberon Sorry I didn't see that. But making it compatible with restify should be easy though since its built on top of express. Any roadmap for this?

**Comment by iCyberon** [comment]
@fr-kshibata I'm not the developer of this module. You should ping @watson for any eta.

_P.S. I'm sure restify isn't built on top of express. They just have many similarities._

**Comment by fr-kshibata** [comment]
@iCyberon I stand corrected. similar :smile:

**Comment by watson** [comment]
@fr-kshibata thanks for reaching out to us, and thank you @iCyberon for jumping in to help :smile: 

Restify support is in the pipeline. I can't put an exact date on it, but hopefully within a couple of months. I'll be sure to let you know when it lands.

I'll label this issue with "restify" for now and leave it open for others to see. I will update this issue when we have something :smiley:

**Comment by fr-kshibata** [comment]
Thank you @watson

**Comment by fr-kshibata** [comment]
Hi @watson any updates for this? 👍

**Comment by watson** [comment]
@fr-kshibata Not yet unfortunately. It's scheduled as our next big framework to add support for, but there are still a few other higher-priority issues that we need to tackle first.

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. 

Restify support was never added to the Opbeat agent though, but if you're interested in trying out Elastic APM, we'll be happy to add support for it there.

Step one is to create a [feature request](https://github.com/elastic/apm-agent-nodejs/issues/new?template=Feature_request.md) in the [Elastic APM Node.js agent](https://github.com/elastic/apm-agent-nodejs) repo.
