### ISSUE TITLE
Opbeat error (400): Unable to validate data

### ISSUE THREAD

**Issue by steverandy** [opbeat/opbeat-node#35]
```
[App:server][Err] Could not notify Opbeat { uuid: undefined }
[App:server][Err] Error: Opbeat error (400): {
    "error_message": "Unable to validate data.", 
    "structured_error": {
        "traces": {
            "groups": {
                "0": {
                    "transaction": "Exceeds max. allowed length of 512 characters"
                }, 
                "1": {
                    "transaction": "Exceeds max. allowed length of 512 characters"
                }, 
                "2": {
                    "transaction": "Exceeds max. allowed length of 512 characters"
                }
            }
        }
    }, 
    "status": 400
}
    at /app/node_modules/opbeat/lib/request.js:11:10
    at IncomingMessage.<anonymous> (/app/node_modules/opbeat-http-client/index.js:44:9)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at instrumented (/app/node_modules/opbeat/lib/instrumentation/async-hooks.js:19:23)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickDomainCallback [as _tickCallback] (node.js:430:17)
```

**Comment by watson** [comment]
@steverandy Thanks for reporting this. It have now been fixed in the latest version (v3.4.1)

**Comment by jesusbotella** [comment]
Hello,

We are experiencing this issue again with version 4.14.1.

The stacktrace shows:
```
Could not notify Opbeat { uuid: undefined }
Error: Opbeat error (400): {
    "status": 400,
    "error_message": "Unable to validate data.",
    "structured_error": {
        "traces": {
            "groups": {
                "85": {
                    "signature": "Exceeds max. allowed length of 512 characters"
                }
            }
        }
    }
}
```

Could it be related to this issue?

Thank you :)

**Comment by watson** [comment]
@jesusbotella thanks for reporting this. Yes, it's related. I thought that we had everything covered with the last fix, but apparently not. I'll just coordinate with the API team to make sure we don't send up any strings that are too long. I'm surprised that you ended up with a trace signature larger than 512 characters though - that's pretty impressive 😀 

I'll report back here when it's fixed.

**Comment by jesusbotella** [comment]
Thank you @watson!

Hahaha, I assume that if the signature is larger than 512 characters is not any good.

**Comment by jesusbotella** [comment]
@watson Is it now fixed or it is just a test? 
If it is fixed, I think that there should be a npm release soon right?

Thank you!

**Comment by watson** [comment]
@jesusbotella I'm in the process of releasing a new version now. I'll let you know

**Comment by watson** [comment]
@jesusbotella it's released now to npm as v4.12.2

**Comment by jesusbotella** [comment]
Thank you so much @watson. We have just installed the update, and we'll be watching it to see if it fails again :)

**Comment by jesusbotella** [comment]
Thank you so much @watson. We have just installed the update, and we'll be
watching it to see if it fails again :)

2017-07-21 14:45 GMT+02:00 Thomas Watson <notifications@github.com>:
