### ISSUE TITLE
Body does not show with hapi

### ISSUE THREAD

**Issue by tanepiper** [opbeat/opbeat-node#36]
When using Hapi and tracking errors, for POST requests instead of seeing a body object I get:

`unavailable: use bodyParser middleware`

There is no documentation on this, especially as Hapi doesn't have the same concept of middleware as express/connect has.

**Comment by watson** [comment]
The agent will look at the incoming http request object for either a `json` or `body` property, which is were Express stores the processed body. I'll have a look if this can be automated for Hapi as well.

Un the mean time, would it possible for you to set any of those properties to the body of the request? That way the Opbeat agent would automatically populate error reports with the body data.

Btw, we are working on a full blown Hapi documentation which will be released soon. But in any case, this particular thing should be handled automatically of cause.

**Comment by AdriVanHoudt** [comment]
I am doing some custom logging atm for errors which I would be happy to PR for and it comes down to:
```js
// logger names comes from the plugin name
			server.on('log', (event, tags) => {

				if (tags.error && !tags.client) { // avoid client errors like disconnects
					if (event.data instanceof Error) {
						opbeat.captureError(event.data, { extra: event, logger: exports.register.attributes.name });
					}
					else {
						opbeat.captureError(event, { logger: exports.register.attributes.name });
					}
				}
			});

			server.on('request-error', (request, error) => {

				// set json manually so we can see the payload in the log
				request.raw.req.json = request.payload;

				// censor password, we don't want it leaking
				if (request.raw.req.json.password) {
					request.raw.req.json.password = 'censored';
				}

				const info = {
					extra: error,
					user: request.auth.credentials,
					request: request.raw.req,
					logger: exports.register.attributes.name
				};

				opbeat.captureError(error, info);
			});
```

**Comment by tanepiper** [comment]
@watson ok, Yea I tried to pass just `http: { body: req.payload}}` but it wanted me to construct the whole http object again.  Would be handy if it the extras used `Object.assign` to merge in existing keys like `url` and `method`.   It was low on my priority list today so I'll pick it up again tomorrow as we're due to go live on Monday with the product.

**Comment by watson** [comment]
@tanepiper what I meant was setting `req.body = req.payload`, but you inspired me to just go ahead and implemented it. So I just released a version that extracts the payload from Hapi requests automatically :smiley: 

Go ahead and upgrade to v3.5.0 and it should just work :smiley:

**Comment by tanepiper** [comment]
:boom: awesome!
