### ISSUE TITLE
Add HTTP proxy setting option or respect the HTTP_PROXY environment variable

### ISSUE THREAD

**Issue by ucin** [opbeat/opbeat-node#39]
I'm behind corporate proxy and this module doesn't work.
I already have proxy setting like this, 

```
process.env.HTTPS_PROXY = 'http://127.0.0.1:3128';
process.env.HTTP_PROXY = 'http://127.0.0.1:3128';
```

but still throw following error 

```
Could not notify Opbeat { uuid: undefined }
   Error: connect ECONNREFUSED 52.4.105.210:443
      at Object.exports._errnoException (util.js:856:11)
      at exports._exceptionWithHostPort (util.js:879:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
```

**Comment by AdriVanHoudt** [comment]
shouldn't your https proxy be actually https?

**Comment by ucin** [comment]
I'm using Cntlm on Windows and redirecting all my HTTPS to Cntlm HTTP. It work for browser.
Also use that setting for `aws-sdk`, with option for SSL is disabled.

```
          ...
          sslEnabled: false,
          httpOptions: {
            proxy: 'http://127.0.0.1:3128',
          },
          ...
```

**Comment by watson** [comment]
@ucin The agent currently doesn't support using a proxy. I've added it to our todo list. Thanks for letting us know about this :smiley:

**Comment by ucin** [comment]
No problem @watson. :+1:

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. The need for a proxy have changed in Elastic APM as you can host the intake API your self, so if you're interested in trying out Elastic APM, we'd love your [feedback](https://discuss.elastic.co/c/apm).
