### ISSUE TITLE
Route naming broken? (hapi)

### ISSUE THREAD

**Issue by AdriVanHoudt** [opbeat/opbeat-node#41]
I had a look at our perf screen and got:
![](http://puu.sh/nOxE4/cd90c63d51.png)
Using hapi 13.x.x and Opbeat 3.6.x

Also (little non related) but what is the best way to give feedback/report issues? here or via email or?

**Comment by watson** [comment]
@AdriVanHoudt In cases like this, it probably makes more sense to either email support@opbeat.com from the email that you have signed up with or message us by clicking the "help" button in the menu when logged in. That way your request gets linked to your account and it's easier for us to see what's going on in your particular case (as it might be related to your specific setup).

I'm looking over all e-mails to support@opbeat.com and I'm online on the chat, so I'll answer there as well :smiley: 

Can I get you do that for this issue? Then I'll take a look.

**Comment by AdriVanHoudt** [comment]
No problem I'll send an email right away
