### ISSUE TITLE
startTransaction manually

### ISSUE THREAD

**Issue by iCyberon** [opbeat/opbeat-node#42]
Hey @watson,

Have a question regarding manual starting of transactions that could be useful when using WebSockets for instance. I saw that `startTransaction` and `endTransaction` methods were added. Can we use these methods? Is there anything else that needs to be done manually to get proper stats? 

Thanks :)

**Comment by watson** [comment]
@iCyberon You can also create custom traces. Note that the API for working with custom traces is still in beta, so it might change in the future. You can read about it here: https://github.com/opbeat/opbeat-node/wiki/Application-Instrumentation#custom-traces

**Comment by pstadler** [comment]
I want to set this up for an service based on the SMTP protocol and I'm wondering if I can simply pass non-HTTP, but SMTP related status codes as result[1]. Could there be some implications or is this possible w/o messing up reporting / alerting in the dashboard?

Anyway, I wanted to thank you for your excellent support so far. Looking forward to attend your talk in Amsterdam this year.

[1] http://www.serversmtp.com/en/smtp-error

**Comment by watson** [comment]
@pstadler if you are referring to the status property on the transaction object, then it's currently just used to display the graphs on the performance pages. All numeric status codes in the 2xx range will be grouped together, all 3xx together and so forth. But it's only used for grouping in the graphs. A non numeric status code will still work though, but it will not be part of the existing groups.

**Comment by pstadler** [comment]
Alright, thank you.
