### ISSUE TITLE
Exclude routes from perf check ?

### ISSUE THREAD

**Issue by mderazon** [opbeat/opbeat-node#43]
Hi, 

Is there a way to exclude routes somehow ?
My `/` route is only used for health check and is periodically getting requests every few seconds.

**Comment by watson** [comment]
@mderazon At the moment, unfortunately no. But I'll mark it as a feature request

**Comment by mderazon** [comment]
to think of it, maybe more natural place for this will be in the dashboard.

**Comment by pstadler** [comment]
I need the exact same functionality as my health check routes are pinged frequently by HAProxy and Uptime Robot. It would therefore be great if there's support for exclude patterns.

**Comment by watson** [comment]
I just thought I'd update you guys on what's going on with this issue. We've scheduled this to be included in an upcoming release probably some time within the next 3 weeks.

**Comment by pstadler** [comment]
Thank you @watson 👍

**Comment by afoninsky** [comment]
@watson any updates on this issue?

**Comment by watson** [comment]
@afoninsky I've been on holiday for a few weeks, but it's on my to-do list for this week 😃

**Comment by watson** [comment]
This feature have now been added to the latest version (v3.17.0). The docs are still not up to date, but check the commit message for 4123e01df2bd1194c7e8f17afe119e61bc72a380. Also, here's a simple usage example:

```js
require('opbeat').start({
  ignoreUrls: [
    '/ping',
    /^\/admin\//i
  ]
})
```

**Comment by watson** [comment]
... as an added bonus, it's also possible to filter based on User-Agent using the new `ignoreUserAgents` option 😄

**Comment by pstadler** [comment]
Works like a charm. Thank you 👍

**Comment by watson** [comment]
Oh, forgot to mention that the new docs are now online: https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#ignoreurls
