### ISSUE TITLE
New version causes timeout in express

### ISSUE THREAD

**Issue by mdcarter** [opbeat/opbeat-node#46]
Version 3.6.8 cause every call to an express app to timeout =/
Don't know the underlying cause, but it's a big issue

**Comment by watson** [comment]
There is an issue with certain promises not resolving in the version 3.6.8. We obviously dropped the ball here and we should have had tests in place to catch this. For now we have reverted the changes made to the Promise instrumentation and released it as version 3.6.9 on npm. When we know exactly what's going on we'll improve the tests to catch these issues.
