### ISSUE TITLE
I am getting the 400 error when attempting to post to opbeat. Am I missing something in the documentation? 

### ISSUE THREAD

**Issue by Joelio7** [opbeat/opbeat-node#47]
Everything works until I try to add stacktrace. Below is the format that prints to console but I am not sure whats deviating from the opbeat stacktrace example?

/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Connected to the target VM, address: '127.0.0.1:50079', transport: 'socket'
Application Starting
{
  "message": "worked",
  "level": "error",
  "exception": {
    "value": "My Test Exception",
    "type": "java.io.IOException",
    "module": "java.io.IOException"
  },
  "extra": {
    "environment": "PRODUCTION",
    "Application": "xxxxx",
    "timestamp": "2016-05-25T16:34+0000"
  },
  "stacktrace": {
    "frames": [
      {
        "filename": "ProgramJava",
        "lineno": "43"
      }
    ]
  }
}java.io.IOException: Server returned HTTP response code: 400 for URL: https://intake.opbeat

**Comment by watson** [comment]
Are you using the node opbeat agent from npm or do you use a 3rd party Java agent?

**Comment by Joelio7** [comment]
Sorry, it's working now. The problem I was trying to pass my lineno as a string instead of a number. Thanks for the quick response though!
