### ISSUE TITLE
ioredis module

### ISSUE THREAD

**Issue by dickeyxxx** [opbeat/opbeat-node#58]
feature request :)

**Comment by watson** [comment]
@dickeyxxx Good idea 😃 I'll add it to our roadmap.

Until this get's added it's possible for you to add custom traces if there's specific things you want to trace in your code. You can read more about it here: https://github.com/opbeat/opbeat-node/wiki/Application-Instrumentation

**Comment by watson** [comment]
@dickeyxxx Just released support for `ioredis`. We currently don't support anything older than the v2.x branch. I hope this is sufficient 😃

To take advantage of this new feature, upgrade your opbeat module to v3.13.0 or newer.

**Comment by AdriVanHoudt** [comment]
@watson we need to get the hapi thing sorted out because I really want this :O (we use ioredis)
