### ISSUE TITLE
hapi error logging

### ISSUE THREAD

**Issue by AdriVanHoudt** [opbeat/opbeat-node#61]
This is a follow up to #59 

So what I have is this:

``` js
server.on('log', (event, tags) => {

    if (tags.error && !tags.client) {
        const info = {
            extra: event,
            logger: exports.register.attributes.name
        };

// super useful for when you are logging with a bunch of tags
        info.extra.tags = tags;

        if (event.data instanceof Error) {
            this.options.opbeat.captureError(event.data, info);
        }
        else {
            this.options.opbeat.captureError(event, info);
        }
    }
});

server.on('request', (request, event, tags) => {

    if (tags.error && !tags.client) {

        const info = {
            extra: event,
            user: request.auth.credentials,
            request: request.raw.req,
            logger: exports.register.attributes.name
        };

        info.extra.tags = tags;

        if (event.data instanceof Error) {
            this.options.opbeat.captureError(event.data, info);
        }
        else {
            this.options.opbeat.captureError(event, info);
        }
    }
});

server.on('request-error', (request, error) => {

        // censor password, we don't want it leaking
// while posting I realised this should also be done on `on('request', ...)`
        if (request.raw.req && request.raw.req.json && request.raw.req.json.password) {
            request.raw.req.json.password = 'CENSORED';
        }

        const info = {
            extra: error,
            user: request.auth.credentials,
            request: request.raw.req,
            logger: exports.register.attributes.name
        };

        this.options.opbeat.captureError(error, info);
});
```

I have this in a plugin so `exports.register.attributes.name` is something custom.
In general I ignore client errors since they do not hold much information but maybe that is me.
As to #59 would it be possible to make it optional? Right now I can't up my version since it will double log (unless Opbeat dedupes it in the backend?)

**Comment by watson** [comment]
Thanks 😃 I can see there's a few things we can improve with our built-in hapi support to make the experience even better.

First a few questions for me to better understand your implementation:

1. What do you use the `logger` info for on the errors and would it be ok to not have this?
1. Is `tags.client` a standard hapi tag or one you have created your self and would you say it makes sense for others to never send those errors to Opbeat?
1. As far as I understand, `request.auth.credentials` is standard in hapi, right?
1. Is `event` guaranteed always to be an object?

To solve the filtering of sensitive information, you can use the [filter option](https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#filter) instead. This allows you to remove passwords etc. across all errors to matter how they are caught.

**Comment by AdriVanHoudt** [comment]
1. I do some logging and analytics in a plugin and I pass that, mainly because I can, the most important info is the machine (which is auto set) so yes it would be ok
2. standard hapi one and not sure, afaik those are errors from clients disconnecting and stuff, I will call upon you superior node/error logging exp to decide this ^^
3. yes when a route has a auth strategy and it passes it can, and in 99% of the cases it will, give back credentials, now what those credentials hold is up to the developer in most cases. In my case it is the user object so works out nicely since it has the id, name, email
4. yes, see https://github.com/hapijs/hapi/blob/master/API.md#server-events for more info

And oh nice, did not know about that 😮

**Comment by AdriVanHoudt** [comment]
@watson what is the next step for this? You want a PR or? I can't really update my version since I will get double error logging and I do really want the ioredis support :D

**Comment by AdriVanHoudt** [comment]
@watson it has been 26 days :P any idea on how to progress?
