### ISSUE TITLE
Transaction sampling

### ISSUE THREAD

**Issue by pdufour** [opbeat/opbeat-node#75]
I think it would be very useful to have an option to sample data for transactions. That should allow you to get an accurate representation of the performance of pages without logging the data for every request. I noticed you can turn it on and off https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#instrument but this would include logging it for only a sample of the requests.

**Comment by watson** [comment]
Thank's for you suggestion. Transaction sampling is not on our roadmap. But it's possible for you to ignore certain endpoints via the [`ignoreUrls`](https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#ignoreurls) option.

**Comment by watson** [comment]
Just doing some cleaning and closing this issue for now. Feel free to reopen 😃
