### ISSUE TITLE
express.static.mime.extensions undefined

### ISSUE THREAD

**Issue by sergiofilhowz** [opbeat/opbeat-node#91]
Only occur when i make the require('opbeat')

**Comment by watson** [comment]
@sergiofilhowz Thanks for reporting 😃

Can you be a little more specific? I'm not sure what you mean with `express.static.mime.extensions undefined`

**Comment by sergiofilhowz** [comment]
I use express.static.mime.extensions object to get extension of an uploaded file based on its mimetype.

**Comment by watson** [comment]
@sergiofilhowz I managed to reproduce it locally. I'm working on a fix and will ship it ASAP. Once again thanks for letting us know about this 😃

**Comment by watson** [comment]
@sergiofilhowz This bug have now been fixed in master. I'll publish this to npm as soon as the CI tests passes

**Comment by watson** [comment]
@sergiofilhowz the fix have now been published to npm as v3.19.1. Thanks for informing us 👍
