### ISSUE TITLE
Could not notify Opbeat (502 Error)

### ISSUE THREAD

**Issue by iCyberon** [opbeat/opbeat-node#93]
Hey @watson,

I'm getting random errors. CPU usage is ~4% on each core (16x cores) and ram usage is around 6.5GB/54GB.

Node: v4.6.0
Opbeat: v3.17.2
Express: v4.14.0

```
App 22321 stderr: Could not notify Opbeat { uuid: undefined }
App 22321 stderr: Error: Opbeat error (502): <html>
App 22321 stderr: <head><title>502 Bad Gateway</title></head>
App 22321 stderr: <body bgcolor="white">
App 22321 stderr: <center><h1>502 Bad Gateway</h1></center>
App 22321 stderr: <hr><center>nginx</center>
App 22321 stderr: </body>
App 22321 stderr: </html>
App 22321 stderr:
App 22321 stderr:     at /app/node_modules/opbeat/lib/request.js:29:10
App 22321 stderr:     at IncomingMessage.<anonymous> (/app/node_modules/opbeat/node_modules/opbeat-http-client/index.js:59:9)
App 22321 stderr:     at emitNone (events.js:72:20)
App 22321 stderr:     at IncomingMessage.emit (events.js:166:7)
App 22321 stderr:     at endReadableNT (_stream_readable.js:921:12)
App 22321 stderr:     at instrumented (/app/node_modules/opbeat/lib/instrumentation/index.js:111:27)
App 22321 stderr:     at nextTickCallbackWith2Args (node.js:476:9)
App 22321 stderr:     at process._tickCallback (node.js:390:17)
```

**Comment by watson** [comment]
We had a minor outage [this morning](http://status.opbeat.com/incidents/mdk1xskc9s51). The incident should have been resolved now and we have not had any issues since 07:35 CET.

You can always check http://status.opbeat.com or follow [@OpbeatStatus](https://twitter.com/OpbeatStatus) on Twitter to see or get notified of our platform status.

**Comment by iCyberon** [comment]
Oh, no problem. Thought, it's a bug, hence reported :)

**Comment by watson** [comment]
@iCyberon No worries, please don't hesitate to contact us if there's anything odd happening 👍 Though we try to be aware of all issues our selfs as they happen, we might miss something and can always improve 😃

In this case I was actually wrong and there were a few 502's that slipped under our radar around 12-o'clock. It was only after I commented above that we discovered it. Once again, sorry for causing alarm. This should not affect the stability of your application though.
