### ISSUE TITLE
Promise error

### ISSUE THREAD

**Issue by AdriVanHoudt** [opbeat/opbeat-node#96]
Note that I am using version 3.9.x and running node 4.6.x
Also I am not using any promises, maybe a library is though.

``` js
 You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 RangeError: Maximum call stack size exceeded
     at wrappedPromise.propagateAslWrapper (/home/adri/Server/node_modules/opbeat/lib/instrumentation/async-hooks.js:372:35)
     at wrappedPromise.proxyWrapper [as __asl_wrapper] (/home/adri/Server/node_modules/opbeat/lib/instrumentation/async-hooks.js:375:31)
     at wrappedPromise.proxyWrapper [as __asl_wrapper] (/home/adri/Server/node_modules/async-listener/index.js:445:19)
   ... X 3000 of these lines
```

**Comment by watson** [comment]
Thanks for the report.

This seems to be an error [logged by pm2]https://github.com/Unitech/pm2/blob/89660095166f06013fe64edb6cac93ea6a3a21b8/lib/ProcessContainer.js#L216).

I'm still looking into why it says `RangeError: Maximum call stack size exceeded` though.

**Comment by watson** [comment]
The promise instrumentation logic have been updated a lot since version 3.9.0, so even if this is Opbeat related, I would really like to see if it hasn't already been fixed in a later version of the agent.

**Comment by watson** [comment]
​Opbeat doesn't currently listen for and report unhandled rejections (maybe this would be a nice feature btw). But Node.js shouldn't crash on unhandled rejections either. So either pm2 is forcing a crash when an unhandled rejection is seen, or it's something that happens just after the unhandled rejection.

So far I've been unable to reproduce this my self, so if you could provide a code snippet that successfully reproduces this bug, it would help a lot 😃

**Comment by AdriVanHoudt** [comment]
Yeah this is a `only happens in production error` :P and I can try updating but it will start logging errors twice since the hapi PR is not there yet but that is better then crashing :P

**Comment by NewUser123123** [comment]
Hello

**Comment by AdriVanHoudt** [comment]
Updating to the latest version seems to have solved this

**Comment by watson** [comment]
@AdriVanHoudt glad to hear that 😃
